field: b0a51bbc-452f-4c28-90cb-be69261fa068 # Mixed Content
fieldLayouts:
  102101fe-01a2-4bca-bf83-3955809ce635:
    tabs:
      -
        elements:
          -
            fieldUid: faf93cfc-3cbf-4eaa-bd2d-16952cde36db # Entries
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54415e1c-11da-4290-ab35-88991089ff7c
            warning: null
            width: 100
          -
            fieldUid: d77dcb20-938f-42b0-8c62-deed91622131 # Show Listing Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1470c7ef-577f-4dc1-b0a5-7ec29cdb5149
            warning: null
            width: 50
          -
            fieldUid: 91922a85-68db-4cd1-a6a0-54a12b645469 # Show Listing Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ce1f50c-bcd0-4023-8989-4e0a53d6dcb9
            warning: null
            width: 50
        name: Content
        uid: 418411af-99e8-4f06-8157-efce4c7023bd
fields:
  91922a85-68db-4cd1-a6a0-54a12b645469: # Show Listing Excerpt
    columnSuffix: xindqofy
    contentColumnType: boolean
    fieldGroup: null
    handle: showListingExcerpt
    instructions: null
    name: 'Show Listing Excerpt'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  d77dcb20-938f-42b0-8c62-deed91622131: # Show Listing Image
    columnSuffix: vnotrqhy
    contentColumnType: boolean
    fieldGroup: null
    handle: showListingImage
    instructions: null
    name: 'Show Listing Image'
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  faf93cfc-3cbf-4eaa-bd2d-16952cde36db: # Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Choose other pages on this site you want to feature here...'
    name: Entries
    searchable: true
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 3
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Choose Entries'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: entries
name: Entries
sortOrder: 8
