field: b0a51bbc-452f-4c28-90cb-be69261fa068 # Mixed Content
fieldLayouts:
  ce64eb04-8963-4e7d-9945-4610ee0f0c2c:
    tabs:
      -
        elements:
          -
            fieldUid: 75d17d41-4e28-4fbc-90ae-74102376b880 # Link URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b519be90-b5bc-484a-8278-0e1e276736c7
            warning: null
            width: 50
          -
            fieldUid: db0b4568-9841-48bd-a7be-a5d617cbf01b # Link Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bbf6680-62d4-4adb-bd34-8cd2df4c6b13
            warning: null
            width: 50
          -
            fieldUid: b582704c-66aa-4611-a6e1-79f208db6ab7 # Link Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83e154c2-4f04-4b3f-8b60-481e29f76b99
            warning: null
            width: 100
        name: Content
        uid: 402e1be7-78fe-442b-b669-05f5eb45e7ef
fields:
  75d17d41-4e28-4fbc-90ae-74102376b880: # Link URL
    columnSuffix: hddtcmes
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: 'A full URL to any page on the internet'
    name: 'Link URL'
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  b582704c-66aa-4611-a6e1-79f208db6ab7: # Link Description
    columnSuffix: gayndchv
    contentColumnType: text
    fieldGroup: null
    handle: linkDescription
    instructions: 'A bit of text to talk about the link'
    name: 'Link Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'e.g., Our favourite search engine should be yours too, try it out!'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  db0b4568-9841-48bd-a7be-a5d617cbf01b: # Link Title
    columnSuffix: bexmnmzk
    contentColumnType: text
    fieldGroup: null
    handle: linkTitle
    instructions: 'The text that you click.'
    name: 'Link Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: featuredLink
name: 'Featured Link'
sortOrder: 9
