field: b0a51bbc-452f-4c28-90cb-be69261fa068 # Mixed Content
fieldLayouts:
  bb05aae9-c53a-4321-98d1-be7a51021c32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6a04ef9a-c473-4a5b-bee9-fd7e5caaa7b4 # Uncropped
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00c3d4bd-597a-429f-be36-c6d15c115639
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3876604f-baf6-4dcb-a75d-380ed5b026b3 # Landscape 3:2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcc18143-a3f3-4c3f-9e41-181df7cb233f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08a13d2e-584d-4d56-a8fe-3b355f04e0c7 # Landscape 16:9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6342a19-6ce8-4b33-8f33-3e321fabde73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5aacad15-f360-4977-9943-6c56e7ceaa59 # Landscape: 2.39:1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc5238c0-1aca-482c-88e2-0aca02477c45
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1cc3093d-fcf8-4128-bb31-74b91aff8630
        userCondition: null
fields:
  5aacad15-f360-4977-9943-6c56e7ceaa59: # Landscape: 2.39:1
    columnSuffix: jvuuzcgs
    contentColumnType: string
    fieldGroup: null
    handle: landscape2391
    instructions: 'The image will be cropped to a 2.39:1 ratio (like a movie)'
    name: 'Landscape: 2.39:1'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6a04ef9a-c473-4a5b-bee9-fd7e5caaa7b4: # Uncropped
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: uncropped
    instructions: 'The image will retain the same shape'
    name: Uncropped
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - photos
      branchLimit: null
      defaultUploadLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  08a13d2e-584d-4d56-a8fe-3b355f04e0c7: # Landscape 16:9
    columnSuffix: xswldgsn
    contentColumnType: string
    fieldGroup: null
    handle: landscape169
    instructions: 'The image will be cropped to a 16:9 ratio (like a TV)'
    name: 'Landscape 16:9'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - photos
      branchLimit: null
      defaultUploadLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  3876604f-baf6-4dcb-a75d-380ed5b026b3: # Landscape 3:2
    columnSuffix: ipyzzpfd
    contentColumnType: string
    fieldGroup: null
    handle: landscape32
    instructions: 'The image will be cropped to a 3:2 ratio (like a photo)'
    name: 'Landscape 3:2'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - photos
      branchLimit: null
      defaultUploadLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageSingle
name: 'Image: Single'
sortOrder: 4
