field: b0a51bbc-452f-4c28-90cb-be69261fa068 # Mixed Content
fieldLayouts:
  07479a44-54c5-49e1-ad9f-822a8e503230:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1379f9c8-bd39-49e2-b499-6c9c2a67936b # Rich Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ab340b8-ecf8-45b1-a00b-0c5fbbfb4d4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fc9fe069-509c-41d5-ab17-fb401bf818e1 # Allow hard to read line lengths
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe82b93-73d5-4998-bca9-010b24c5f623
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7cce2f73-676c-4b0f-8514-d9a26ed46c25
        userCondition: null
fields:
  1379f9c8-bd39-49e2-b499-6c9c2a67936b: # Rich Text
    columnSuffix: ubopbcnt
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: 'You can use the formatting buttons to create things like headings, paragraphs, and lists.'
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: aea5ff6c-2e97-4659-b273-30e7258dd14d # Default
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  fc9fe069-509c-41d5-ab17-fb401bf818e1: # Allow hard to read line lengths
    columnSuffix: qwbzrwnz
    contentColumnType: boolean
    fieldGroup: null
    handle: allowHardToReadLineLengths
    instructions: 'Only turn this on if you''re happy with very long lines of text on wider screens.'
    name: 'Allow hard to read line lengths'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: richText
name: 'Rich Text'
sortOrder: 1
