field: b0a51bbc-452f-4c28-90cb-be69261fa068 # Mixed Content
fieldLayouts:
  073e74ad-1bfb-4435-b122-b3fa209b085b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f6b9e281-1629-4b01-9358-328790bed358 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e93c3af-41ad-4c38-9031-478e46e724a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 303f6bf0-2c29-459c-afef-f03fb0298d24 # Text Position
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae7e300a-a832-4344-af89-adc55eba3fb3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2b187454-5e81-41a2-bb5a-67f435df8ad2 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fd9f236-89ca-4743-b0f1-317791aa0b29
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9d7f6cee-b6c7-4558-bfd9-79804796377d # Expansion Method
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c50c8601-9e92-4972-87e2-d786402a4fc8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b9e49baa-2b82-473f-a1d5-f5670a422921
        userCondition: null
fields:
  2b187454-5e81-41a2-bb5a-67f435df8ad2: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Choose an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9d7f6cee-b6c7-4558-bfd9-79804796377d: # Expansion Method
    columnSuffix: gmdvecna
    contentColumnType: string
    fieldGroup: null
    handle: expansionMethod
    instructions: 'When you have text that''s taller than the image would be when they are side by side, how should the image behave?'
    name: 'Expansion Method'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Scale to fill'
            -
              - value
              - scaleToFill
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Stay at the top'
            -
              - value
              - stayAtTheTop
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Stay in the middle'
            -
              - value
              - stayInTheMiddle
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Stay at the bottom'
            -
              - value
              - stayAtTheBottom
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  303f6bf0-2c29-459c-afef-f03fb0298d24: # Text Position
    columnSuffix: utvketff
    contentColumnType: string
    fieldGroup: null
    handle: textPosition
    instructions: null
    name: 'Text Position'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f6b9e281-1629-4b01-9358-328790bed358: # Text
    columnSuffix: dbmcgjzv
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: aea5ff6c-2e97-4659-b273-30e7258dd14d # Default
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: textByImage
name: 'Text By Image'
sortOrder: 3
