fieldLayouts:
  2b7cd1e3-c9ed-48f3-95a6-a10fea7f5b96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 96427509-56d3-46a8-8d0d-d8d39e7a6de9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e17983f8-744e-49ef-9eae-e9480693cebc # Email Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 577364bf-1305-4e07-85f3-9c81c1f80651
            userCondition: null
            warning: null
            width: 100
        name: Defaults
        uid: 5f573bf3-60e8-4917-a6bd-7808f50d6041
        userCondition: null
handle: email
hasTitleField: false
name: Email
section: f1d8fe85-91fd-4f12-9b2e-b04e172ed43d # Email
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
