fieldLayouts:
  ddcc8cb0-6f75-430d-ae1e-c28c49793478:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0931c771-a7a4-49ed-9725-0314bb776335
            warning: null
            width: 100
        name: Content
        uid: ba8ddb72-4ea8-4e37-a68a-869e66f6cd48
      -
        elements:
          -
            fieldUid: 4b265d58-9bcb-446a-8339-a25f3f625338 # Listing Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 450bbc64-ce74-40c2-ad44-e444b0660895
            warning: null
            width: 100
          -
            fieldUid: e5bed996-6c75-4bf7-bb8e-3f7765a0bec3 # Listing Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13d54e42-c5c2-4b60-a255-62ae2b5687a5
            warning: null
            width: 100
        name: 'Listing Details'
        uid: 73162e68-9cbc-4c60-9a43-1391d40a5903
      -
        elements:
          -
            fieldUid: 14cfd869-dfee-4009-afee-8350c15d51ad # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64bb75be-d23a-4814-973e-043ed2e6fcdc
            warning: null
            width: 100
        name: SEO
        uid: 76b7f6dd-e8b4-49dd-a176-df3f33415ad2
handle: homepage
hasTitleField: true
name: Homepage
section: 50731a92-0234-47dc-b983-b4d3fa37646f # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
