fieldLayouts:
  03f74d12-a4cd-488f-a51c-b2a5f2a4eae9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dbdfcce4-36f1-4ebc-a460-b413c25e9342
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f87a627c-8252-450e-bedd-74bb08e21d9d # Formatted Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c99a38b7-afe8-44dd-864f-1032be4832b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c964f76-f7db-4765-8c8d-add2047d8ba7 # Missing Image Fallback
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56d178c9-5636-4e21-8ecb-4b5088a8fbda
            userCondition: null
            warning: null
            width: 100
        name: 'General Settings'
        uid: 2e4ea918-2b3f-4c65-bf3d-51ab39f89c8c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 344da3ee-6f97-44b2-b4ae-8decb263506d # Show Newsletter CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 977708c5-41c2-485f-b121-684aa8ab56a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eba994c9-4a51-4ee1-8574-0e9a8d04b1c1 # Newsletter CTA text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbd12dd9-7cc5-4fb8-8a9e-61f53d68cc76
            userCondition: null
            warning: null
            width: 100
        name: Newsletter
        uid: 4b386861-0f98-4074-ba39-da98a4f41d5d
        userCondition: null
handle: website
hasTitleField: false
name: Website
section: 7cfd5653-c4b9-4a46-9471-a2cae1b97003 # Website
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
