headingLevels: false
name: 'Simple with links'
options:
  code:
    indentSequence: ' '
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - bold
  - italic
  - link
