headingLevels:
  - 2
  - 3
  - 4
name: Default
options:
  code:
    indentSequence: ' '
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - bulletedList
  - numberedList
  - link
