columnSuffix: faxkeiyf
contentColumnType: text
fieldGroup: 42d5c4a2-18cd-49bd-8f8e-3f79b84ed7b2 # Common
handle: listingExcerpt
instructions: 'Displayed on listing pages as an introduction to this page. Its job is to entice the visitor to click through and read the full article.'
name: 'Listing Excerpt'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: d40dd4e5-ad74-4354-a28c-e32b99da966c # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
