columnSuffix: ixfrbmcr
contentColumnType: text
fieldGroup: 45d743a2-ba39-4aed-9a6d-b6b90abf971e # Globals
handle: newsletterCtaText
instructions: 'Optional text to go with the newsletter subscription form.'
name: 'Newsletter CTA text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  ckeConfig: aea5ff6c-2e97-4659-b273-30e7258dd14d # Default
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
