dateModified: 1691484642
elementSources:
  craft\elements\Asset:
    -
      disabled: false
      key: 'volume:22079320-7090-4cd8-bbb4-27a18a70f38f' # Images
      tableAttributes:
        - filename
        - alt
        - size
        - dateModified
        - link
      type: native
    -
      key: 'volume:f465523b-77c1-45ed-a308-bffb975c28b4' # Files
      type: native
    -
      key: 'folder:89f726e7-32eb-4093-a391-d30c2d052d0d'
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - dateUpdated
        - uri
      type: native
    -
      heading: Structures
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - 'field:4b265d58-9bcb-446a-8339-a25f3f625338' # Listing Image
        - dateUpdated
        - revisionCreator
        - uri
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:78e1ba52-479b-48f4-b0a6-3659f3838ff1' # Pages
      tableAttributes:
        - 'field:4b265d58-9bcb-446a-8339-a25f3f625338' # Listing Image
        - postDate
        - dateUpdated
        - revisionCreator
        - uri
      type: native
    -
      heading: 'Site Wide'
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 7ce3a8bb-ad5a-4d02-bcf3-517b399c3e4c
            values:
              - f1d8fe85-91fd-4f12-9b2e-b04e172ed43d # Email
              - 7cfd5653-c4b9-4a46-9471-a2cae1b97003 # Website
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:e7907b73-07b3-45e9-9d4c-5632495765fb'
      label: Globals
      tableAttributes: '-'
      type: custom
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: $SYSTEM_SENDER_NAME
  replyToEmail: $SYSTEM_REPLY_TO_ADDRESS
  template: $SYSTEM_HTML_EMAIL_TEMPLATE
  transportSettings:
    encryptionMethod: $SYSTEM_ENCRYPTION_METHOD
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: $SYSTEM_USE_AUTH
    username: $SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  localFileUploads:
    hasUrls: true
    name: 'Local File Uploads'
    settings:
      path: '@primarySiteWebRoot/content/files'
    type: craft\fs\Local
    url: '@primarySiteUrl/content/files'
  localImageUploads:
    hasUrls: true
    name: 'Local Image Uploads'
    settings:
      path: '@primarySiteWebRoot/content/images'
    type: craft\fs\Local
    url: '@primarySiteUrl/content/images'
meta:
  __names__:
    0ad765ce-da18-4b42-8883-7c75e67bc6c7: Files # Files
    0da6de33-e9ae-4ac5-a7dc-63322767738d: Blockquote # Blockquote
    0f6f6a63-845d-449f-b5f6-c0b17a402227: Images # Images
    1b8a29c5-f1bf-4f03-a061-90b6190c1018: Email # Email
    2b187454-5e81-41a2-bb5a-67f435df8ad2: Image # Image
    3d35622b-6607-4a05-81f0-93d712f18eed: 'Minimal UI' # Minimal UI
    4b265d58-9bcb-446a-8339-a25f3f625338: 'Listing Image' # Listing Image
    4ca648ee-78d8-4b4e-be42-119bdc9ac095: Crop # Crop
    5aacad15-f360-4977-9943-6c56e7ceaa59: 'Landscape: 2.39:1' # Landscape: 2.39:1
    5c964f76-f7db-4765-8c8d-add2047d8ba7: 'Missing Image Fallback' # Missing Image Fallback
    5dee40ad-8466-4b85-887a-e0c1862061f8: Code # Code
    5e75ab6f-700d-4d71-a119-8486e41862d4: 'Images: Grid' # Images: Grid
    6a04ef9a-c473-4a5b-bee9-fd7e5caaa7b4: Uncropped # Uncropped
    6ac2852d-9212-4f02-89d2-35cd874150e9: $SYSTEM_NAME # $SYSTEM_NAME
    7cfd5653-c4b9-4a46-9471-a2cae1b97003: Website # Website
    7fe58c02-d209-4e1a-9883-dd49189d500c: Form # Form
    08a13d2e-584d-4d56-a8fe-3b355f04e0c7: 'Landscape 16:9' # Landscape 16:9
    9d7f6cee-b6c7-4558-bfd9-79804796377d: 'Expansion Method' # Expansion Method
    9eca21d8-3abf-426e-b46d-580dcdb2681d: 'Rich Text' # Rich Text
    9f1920f0-78f1-47cd-b259-887b1de32c74: 'Aspect Ratio' # Aspect Ratio
    14cfd869-dfee-4009-afee-8350c15d51ad: SEO # SEO
    36ea2d39-19c7-4446-aeb1-0b3035c5b6c2: 'Image: Single' # Image: Single
    42d5c4a2-18cd-49bd-8f8e-3f79b84ed7b2: Common # Common
    45d743a2-ba39-4aed-9a6d-b6b90abf971e: Globals # Globals
    58a434d4-7519-40ff-ac32-cb573996138a: 'Public Schema' # Public Schema
    61b0742f-4efb-4e9f-be20-3f36c5e70a16: Spacer # Spacer
    61e390b2-9faf-4b6c-9381-6e7f4e207fbb: Code # Code
    68c0b17f-8401-4068-a0b6-10c4781f5744: 'Loop Video' # Loop Video
    72c0afad-ee40-44a9-baa6-18dc30116a7b: Answer # Answer
    75d17d41-4e28-4fbc-90ae-74102376b880: 'Link URL' # Link URL
    78e1ba52-479b-48f4-b0a6-3659f3838ff1: Pages # Pages
    83b0902d-25fa-4ce1-a72b-0857d3f51d45: 'Link To' # Link To
    303f6bf0-2c29-459c-afef-f03fb0298d24: 'Text Position' # Text Position
    344da3ee-6f97-44b2-b4ae-8decb263506d: 'Show Newsletter CTA' # Show Newsletter CTA
    702f0f38-1282-4085-8e00-5baaa7256063: 'Background Image' # Background Image
    1111c868-466c-4b74-ae32-915139c845b1: 'Grid Style' # Grid Style
    1379f9c8-bd39-49e2-b499-6c9c2a67936b: 'Rich Text' # Rich Text
    1865e161-9efb-43b3-a4be-59383a6674f7: Quotation # Quotation
    1976bfb2-6bf2-4f60-91a5-94838c7fcf44: 'Website Admin' # Website Admin
    2219b27c-3104-49fc-9b26-270a35789282: Autoplay # Autoplay
    6079e509-0ab3-4f71-ae20-eae74d724613: 'Spacer Size' # Spacer Size
    8678d15f-e8dc-4773-b25d-947e3c414e3b: Website # Website
    50731a92-0234-47dc-b983-b4d3fa37646f: Homepage # Homepage
    72579a5f-3f21-4476-9c2f-4de146cc0cba: Form # Form
    91922a85-68db-4cd1-a6a0-54a12b645469: 'Show Listing Excerpt' # Show Listing Excerpt
    97151f9f-def3-4806-894b-148bd551342b: 'Text Colour' # Text Colour
    00365143-d8a1-4887-b5af-649d379597ea: Question # Question
    847542b0-c1b3-4237-b5e7-2e4f647c576b: 'Simple with links' # Simple with links
    3876604f-baf6-4dcb-a75d-380ed5b026b3: 'Landscape 3:2' # Landscape 3:2
    22079320-7090-4cd8-bbb4-27a18a70f38f: Images # Images
    a1ad1291-f30b-4c72-9380-081566bacf65: 'Main Navigation' # Main Navigation
    aa3fec5f-bca4-49d9-818a-7e96cac33be9: Images # Images
    ae9dfd77-941c-4707-8fb0-e4fce617b424: 'Youtube/Vimeo Video URL' # Youtube/Vimeo Video URL
    aea5ff6c-2e97-4659-b273-30e7258dd14d: Default # Default
    aec806ed-10ba-4ecd-819e-bd0bd36ca129: 'Featured Link' # Featured Link
    b0a51bbc-452f-4c28-90cb-be69261fa068: 'Mixed Content' # Mixed Content
    b9df2f18-f25a-4f21-a1bd-2d54dd0ce464: 'Column Count' # Column Count
    b331abc3-406d-4f08-9b2c-7c672bf0de0e: Primary # Primary
    b582704c-66aa-4611-a6e1-79f208db6ab7: 'Link Description' # Link Description
    bb1cad82-345d-45ce-8868-7e95321e0dde: Attribution # Attribution
    bb85a1cd-c2b6-49d2-8f4c-221e447e0124: 'Generic Page' # Generic Page
    d0c2725f-cc81-4c85-a467-3179e7b41c85: Entries # Entries
    d9e8808e-2fe2-41ab-b75f-4c7501b6b7d8: 'Public Schema' # Public Schema
    d40dd4e5-ad74-4354-a28c-e32b99da966c: Simple # Simple
    d77dcb20-938f-42b0-8c62-deed91622131: 'Show Listing Image' # Show Listing Image
    db0b4568-9841-48bd-a7be-a5d617cbf01b: 'Link Title' # Link Title
    de2f35a0-9340-455e-bdd1-56d49ee957e9: Video # Video
    e5bed996-6c75-4bf7-bb8e-3f7765a0bec3: 'Listing Excerpt' # Listing Excerpt
    e44a73d4-3acb-4966-9453-c5b048152dd2: 'Text By Image' # Text By Image
    e17983f8-744e-49ef-9eae-e9480693cebc: 'Email Header' # Email Header
    eba994c9-4a51-4ee1-8574-0e9a8d04b1c1: 'Newsletter CTA text' # Newsletter CTA text
    ed578c38-afc8-4e66-b8b8-9dece35fc627: 'Footer Navigation' # Footer Navigation
    f0a903f2-fd7a-4d92-9df6-958587df9b3b: Homepage # Homepage
    f1d8fe85-91fd-4f12-9b2e-b04e172ed43d: Email # Email
    f4eb0191-de34-435f-8f7c-dae20b322c0d: 'Redirect on success' # Redirect on success
    f6b9e281-1629-4b01-9358-328790bed358: Text # Text
    f54d2cc3-2e99-4524-812d-c5a604169d7a: 'Question and Answer' # Question and Answer
    f87a627c-8252-450e-bedd-74bb08e21d9d: 'Formatted Address' # Formatted Address
    f105a959-ff7b-4aa4-bee5-de61ffe7843d: Files # Files
    f465523b-77c1-45ed-a308-bffb975c28b4: Files # Files
    faf93cfc-3cbf-4eaa-bd2d-16952cde36db: Entries # Entries
    fb6bb926-0792-4a1f-804a-cca44724ce74: 'Images: Slider' # Images: Slider
    fc9fe069-509c-41d5-ab17-fb401bf818e1: 'Allow hard to read line lengths' # Allow hard to read line lengths
    ff214a18-a91f-4bdf-b3bf-2904b0be331a: 'Public Schema' # Public Schema
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: $LICENSE_KEY_BLITZ
    schemaVersion: 4.5.0
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  hyper:
    edition: standard
    enabled: true
    licenseKey: $LICENSE_KEY_HYPER
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      assetSourceSettings:
        1:
          __assoc__:
            -
              - enabled
              - '1'
            -
              - imageWidth
              - '2200'
            -
              - imageHeight
              - '2200'
            -
              - imageQuality
              - '90'
        2:
          __assoc__:
            -
              - enabled
              - '1'
            -
              - imageWidth
              - ''
            -
              - imageHeight
              - ''
            -
              - imageQuality
              - ''
      enabled: true
      imageHeight: 2200
      imageQuality: 90
      imageWidth: 2200
      nonDestructiveCrop: false
      nonDestructiveResize: false
      skipLarger: true
  imager-x:
    edition: pro
    enabled: true
    licenseKey: $LICENSE_KEY_IMAGERX
    schemaVersion: 4.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: $LICENSE_KEY_NAVIGATION
    schemaVersion: 2.0.7
  seomatic:
    edition: standard
    enabled: true
    licenseKey: $LICENSE_KEY_SEOMATIC
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: local
      excludeNonCanonicalUrls: false
      generatorEnabled: false
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
  simplemap:
    edition: lite
    enabled: false
    schemaVersion: 3.4.2
    settings:
      apiKey: null
      browserApiKey: null
      disablePopulateMissingFieldData: false
      geoLocationAutoRedirect: false
      geoLocationCacheDuration: 5274000
      geoLocationService: none
      geoLocationToken: ''
      geoService: google
      geoToken: ''
      mapTiles: google.roadmap
      mapToken: ''
      serverApiKey: null
      unrestrictedApiKey: null
      w3wEnabled: false
      w3wToken: ''
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  wheelform:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      cp_label: Forms
      disabled_fields:
        - file
        - hidden
        - list
        - number
        - html
      from_email: from@website.com
      from_name: Website
      recaptcha_min_score: '0.5'
      recaptcha_public: ''
      recaptcha_secret: ''
      recaptcha_version: '2'
      success_message: 'Thank You! we will review your submission shortly.'
      volume_id: ''
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: Europe/London
